### ISSUE TITLE
adobeMobileLibrary does not compile against latest Android Tools SDK

### ISSUE THREAD

**Issue by andresesfm** [Adobe-Marketing-Cloud/mobile-services#103]
Error while compiling is:
Unknown source file : Uncaught translation error: com.android.dx.cf.code.SimException: com.android.dx.rop.cst.CstMethodRef cannot be cast to com.android.dx.rop.cst.CstInterfaceMethodRef
Unknown source file : Uncaught translation error: com.android.dx.cf.code.SimException: com.android.dx.rop.cst.CstMethodRef cannot be cast to com.android.dx.rop.cst.CstInterfaceMethodRef

Fix is to re-compile using latest Google Play Services according to: https://code.google.com/p/android/issues/detail?id=187483

**Comment by shalehaha** [comment]
@andresesfm,
Thanks for the feedback, this is a known issue and will be fixed in the next release.

**Jiabin Geng**
*Mobile Engineer*
[Adobe Marketing Cloud](http://www.adobe.com/solutions/digital-marketing.html)

**Comment by shalehaha** [comment]
Fixed on 4.8.0 release.

**Comment by bearprada** [comment]
@shalehaha i want to know how to fix this issue

**Comment by sbenedicadb** [comment]
Hey @bearprada, are you using SDK version 4.8.0 or newer?

**Comment by bearprada** [comment]
I have used the latest version which does not have this compile problem. I just curious "how" to fix it.

**Comment by shalehaha** [comment]
@bearprada,
It depends on how you are using google play services libs, usually you can fix it by recompiling you product against the latest play-services libs.
But for our library, we are actually using reflection to call google play-services API since we have no idea on which version of play-services our client will be using.
Hope this answers your question. Thanks.
