### ISSUE TITLE
Issues sending "" (empty string) value especially when trying to send Pipe delimited values

### ISSUE THREAD

**Issue by scottbullock3** [Adobe-Marketing-Cloud/mobile-services#138]
We are seeing an issue with adobeMobileLibrary-4.8.2 for Android.  When assigning the value of an empty string “” to a field in the map, the field is not getting sent.  It looks as if it is treating the value as a null. This is especially a problem when we are trying to send a pipe delimited value and in the cases that the first value is empty string the field will not send. 

Example:

String firstValue = “”;
String secondValue = “TV Show”;

String finalValue = firstValue + “|” + secondValue;

fieldMap.put(“FieldName”, finalValue)

//FieldName will not be sent with the rest of the values on the field map.

**Comment by shalehaha** [comment]
@scottbullock3,

It's expected that SDK is ruling out the kv pairs with an empty value string.

But in your example, FieldName should be sent since it's not empty. Here is what I believe should be happening:
String firstValue = “”;
String secondValue = “TV Show”;
String finalValue = firstValue + “|” + secondValue;

fieldMap.put(“firstValue”, firstValue);    // not be sent, because it's empty
fieldMap.put(“secondValue”, secondValue);  // be sent 
fieldMap.put(“FieldName”, finalValue);  // be sent 

- Jiabin

**Comment by agbison** [comment]
This is a change in behavior in the SDK, are you planning on fixing or should we make a change client side to address.  This is blocking us from being on most recent version.

**Comment by shalehaha** [comment]
@agbison,

This is the expected behavior of SDK. There was a bug in SDK that it was sending out the data even the value is empty, and we have fixed it.
So I think it is something you guys need to address on your side.

However, I wanted to know why it's block issue for you, could you please explain a bit more about it? Thanks.

Jiabin

**Comment by agbison** [comment]
its blocking since the "bug" we were using as a feature and expected behavior.  This was undocumented apparently and is a breaking change for our omniture pipeline.  We will address on our side this change.

**Comment by shalehaha** [comment]
@agbison ,
Thanks for your feedback, we will definitely be doing better on the documentation.
