### ISSUE TITLE
Is there an iOS SDK equivalent to the Android SDK Config class method pauseCollectingLifecycleData?

### ISSUE THREAD

**Issue by patakijv** [Adobe-Marketing-Cloud/mobile-services#145]
In the Android SDK there is a Config class method **pauseCollectingLifecycleData** for pausing the collecting of the lifecycle data as demonstrated in this example https://github.com/Adobe-Marketing-Cloud/mobile-services/blob/ce5cda48c5f4ecb11ab9288b3778895efa2de5cd/samples/Android/ADBMobileSamples/src/com/adobe/adbmobilesamples/LifetimeValueActivity.java#L43 

I don't find anything similar in the SDK or Samples for iOS.

Is there a different way to handle this on iOS or is there a better explanation as to why iOS doesn't require this or can't do the same thing?

**Comment by sbenedicadb** [comment]
Hey @patakijv,

The application lifecycle in iOS works in a way that allows us to automatically detect when an equivalent method to `pauseCollectingLifecycleData` should be called.  As such, there is no need to expose this method publicly.

In Android, because your app is comprised of a collection of Activities, and your user may potentially enter or exit your app from any of those Activities, each Activity is required to notify the SDK of application lifecycle events (via calling `collectLifecycleData` in `onResume` and `pauseCollectingLifecycleData` in `onPause`).

Hope this helps.

-steveb
