### ISSUE TITLE
Any Referrer Not Received through Marketing Link 

### ISSUE THREAD

**Issue by hiasakura** [Adobe-Marketing-Cloud/mobile-services#168]
Hi Team

I created the marketing link for android vid Mobile Service UI as follows:
https://c00.adobe.com/v3/8a073e49171cb11017fb914ee3f5b4c391f2de6d5a6a6ef5f9437b102e366f68/start?a_dl=57a902ac28dc277a4d6f6ca1

Even though it seems that the implementation fits into the help page and test it accrodingly, any referrer information can not be sent on the initial launch.
https://marketing.adobe.com/resources/help/en_US/mobile/android/t_testing-marketing-link-acquisition.html
https://marketing.adobe.com/resources/help/en_US/mobile/android/t_testing-marketing-link-acquisition.html

Here is my code:
https://github.com/hiasakura/Android_Adobe_Sample/tree/master/AndroidStudioProjects/ShoppingDemoEx
・TopActivity.java: Main Activity Class. Set Lifecycle Collection.
・GPBroadcastReceiver: Receiver Class.
・ADBMobileConfig.json: acquisition & referrerTimeout have set properly
・AndroidManifest.xml: "net.hiroasak.shoppingdemoex.GPBroadcastReceiver" is set

It would be really appreciated if you could advice on  the implementation, missing something on my code.
(ie) My Android App does not work for SSL but Marketing Link has been provided for SSL. Is this related ?

**Comment by sp-adobe** [comment]
Hey @hiasakura,

In `TopActivity.java` (https://github.com/hiasakura/Android_Adobe_Sample/blob/master/AndroidStudioProjects/ShoppingDemoEx/app/src/main/java/net/hiroasak/shoppingdemoex/TopActivity.java) in your ShoppingDemoEx app, `Analytics.trackState()` in `onCreate()` (https://github.com/hiasakura/Android_Adobe_Sample/blob/master/AndroidStudioProjects/ShoppingDemoEx/app/src/main/java/net/hiroasak/shoppingdemoex/TopActivity.java#L108) is called before `Config.collectLifecycleData()` in `onResume()` (https://github.com/hiasakura/Android_Adobe_Sample/blob/master/AndroidStudioProjects/ShoppingDemoEx/app/src/main/java/net/hiroasak/shoppingdemoex/TopActivity.java#L173). This causes the referrer information to be sent with the trackState() request instead of the Lifecycle launch request. Please ensure that `collectLifecycleData()` is called before other analytics track methods.

> My Android App does not work for SSL but Marketing Link has been provided for SSL
Are you referring to the `"ssl": false` setting under `"analytics"` in `ADBMobileConfig.json`? This setting does not affect the Acquisition feature.

Smit Patel
Mobile Software Engineer
Adobe Marketing Cloud

**Comment by sp-adobe** [comment]
Hey @hiasakura, was this issue resolved?
