### ISSUE TITLE
Crash: ADBMobile initWithWebViewEngine:

### ISSUE THREAD

**Issue by dani-inside** [Adobe-Marketing-Cloud/mobile-services#178]
Hi

I've integrated the ADBMobile into a Cordova/Ionic app. Unfortunately, the app crashes immediately after start, as soon as ADBMobile tries to initialize. 

`2016-09-22 09:40:09.371347 myApp[1636:743444] -[ADBMobile initWithWebViewEngine:]: unrecognized selector sent to instance 0x170006420
2016-09-22 09:40:09.371739 myApp[1636:743444] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[ADBMobile initWithWebViewEngine:]: unrecognized selector sent to instance 0x170006420'
*** First throw call stack:
(0x182c441c0 0x18167c55c 0x182c4b278 0x182c48278 0x182b4259c 0x10020f1c4 0x10020d2d0 0x1000b9244 0x188a8c5c8 0x188a8c190 0x188a9293c 0x188a8fddc 0x188b02604 0x100210a8c 0x1000b8f60 0x188afe61c 0x188d0ed60 0x188d14ad0 0x188d29270 0x188d11ab4 0x1847e5904 0x1847e5770 0x1847e5b18 0x182bf2278 0x182bf1bc0 0x182bef7c0 0x182b1e048 0x188af77cc 0x188af2550 0x1000b8e50 0x181b005b8)
libc++abi.dylib: terminating with uncaught exception of type NSException`

Any ideas? Thanks, much appreciated.

**Comment by sbenedicadb** [comment]
Hey @dani-inside,

The method called in your log, `[ADBMobile initWithWebViewEngine:]`, is not in the SDK.  This is why you are getting the exception.

I realize that since you are building a Cordova app, this is probably not a method that you've called manually.  I will investigate internally to see if I can find where this issue originates so we can get a fix for you.

Thanks for your patience.

**steve benedick**
*sr mobile software engineer*
[Adobe Marketing Cloud](http://www.adobe.com/solutions/digital-marketing.html)

**Comment by dani-inside** [comment]
Thanks @sbenedicadb. Meanwhile I've tried with a 3rd party plugin, which is working fine. Tracking fully working now. Find it here if you're interested: https://github.com/Imagitas/adb-mobile-services

**Comment by sbenedicadb** [comment]
@dani-inside,

Can you give me a little more information about the environment you were running when that method got called from your app?  

If you would you be willing to provide steps to reproduce it, we would be very appreciative.  If so, please contact [client care](http://helpx.adobe.com/marketing-cloud/contact-support.html) to open an issue.  Thanks!

-steveb
