### ISSUE TITLE
Tag and page name not displaying on bloodhound. Please check the configuration and update us.

### ISSUE THREAD

**Issue by rajesh57** [Adobe-Marketing-Cloud/mobile-services#192]
@sbenedicadb Thanks for the update ,

Successfully installed Bloodhound in my MAC now. But Tag and event name not displaying.

Following this configuration
https://marketing.adobe.com/resources/help/en_US/mobile/bloodhound/ssl.html

1.http://serverIP:50000/ - downloaded certificate when I hit on browser and installed.

ADBMobileConfig.json - following changes done
{
"version" : "1.0",
"analytics" : {
"rsids" : "cbgiosdev",
"server" : "localhost:50000",
"charset" : "UTF-8",
"ssl" : false,
// "ssl" : true,
"offlineEnabled" : true,
"lifecycleTimeout" : 300,
"privacyDefault" : "optedin",
"poi" : []
},
"target" : {
"clientCode" : "",
"timeout" : 5
},
"audienceManager" : {
"server" : ""
}
}

Still I can't find any tag on bloodhound software. Please assist me any configuration missed out.
Attached screen shot for your reference.

Kindly respond ASAP.
Thanks in advance !!!.
![7f19ea78-b237-11e6-8507-34117d9795b4](https://cloud.githubusercontent.com/assets/1791931/20659205/221043d4-b568-11e6-8948-5e3f07fe95f3.png)
![7f173422-b237-11e6-9ce1-b10fb7ca6fd9](https://cloud.githubusercontent.com/assets/1791931/20659206/22156d3c-b568-11e6-827a-c8e7a00adfea.png)

**Comment by sbenedicadb** [comment]
Hey @rajesh57,

If you're not using SSL, you won't need the Bloodhound CA cert.  I can't tell for sure what your intentions are, because your config file has `// "ssl":true` in it...looks like you maybe have tried both?  Either way, if you're just doing HTTP, then you shouldn't need to have the cert installed.  

I noticed that next to the Bloodhound IP address on the top of your screen you have a yellow dot.  This indicates that Bloodhound was unable to start the proxy server.  I would recommend trying a different option from the Server dropdown, then hitting the start button.  If the server is running properly, you will have a green dot next to the address.

Another good thing to verify is that your target device (or simulator) can reach the Bloodhound server.  To do this, you can open a web browser on your device and enter in Bloodhound's IP and port.  If all is working properly, your browser will show a "Bloodhound Info" screen.

Hope this helps.

**steve benedick**
*sr mobile software engineer*
[Adobe Marketing Cloud](http://www.adobe.com/solutions/digital-marketing.html)
