### ISSUE TITLE
iOS - ADBMobileUpdateLastKnownTimeStamp and system UserDefaults

### ISSUE THREAD

**Issue by taiyungo** [Adobe-Marketing-Cloud/mobile-services#196]
<img width="706" alt="screen shot 2016-12-16 at 3 15 08 pm" src="https://cloud.githubusercontent.com/assets/20499416/21255339/44b5e3b6-c3a6-11e6-8b30-d943fc644148.png">

According to the system, the UserDefaults didChangeNotification is guaranteed to be posted on the main thread however, when adobe changes the UserDefaults it seems like it is catching the didChangeNotification and posting it again on another queue than the main queue which can result in unexpected behavior as the consumer of the framework always expect the didChangeNotification to be posted on the main thread.

**Comment by shalehaha** [comment]
@taiyungo,

I'd guess it is more of an Apple's documentation issue. During my test, it posts the notification to  the same thread where the changes of UserDefaults happening, instead of the main queue. 

For example in the screenshot, I changed the UserDefault in a background thread, and you can notice that the callback was triggered on the same background thread.
![screen shot 2017-01-23 at 4 06 22 pm](https://cloud.githubusercontent.com/assets/2831856/22227100/b8ea0124-e186-11e6-9e20-c3c6c08224d7.png)

So I think in your app you have to dispatch your code onto the main queue if needed.
Thanks, please let us know if you have any further questions. 

Jiabin
