### ISSUE TITLE
Carthage support

### ISSUE THREAD

**Issue by MadsBogeskov** [Adobe-Marketing-Cloud/mobile-services#220]
Would it be possible for you to add Carthage support?

**Comment by shalehaha** [comment]
@MadsBogeskov,
I created an internal ticket for it and we will look into the possibility of  Carthage support. Will update this ticket once we have an update. Thanks.

**Comment by blender** [comment]
So... how long has this ticket been pending exactly?

**Comment by claudiogomezGL** [comment]
Any progress in this issue?
I really needed for Carthage.

**Comment by hunterpeterson** [comment]
@claudiogomezGL,
The internal ticket is still pending. We have a large backlog of features and support, with Carthage living in the middle ground of that backlog. For transparency Carthage support is not in our 2018 first half roadmap. Thank you for jumping in and giving a +1 on Carthage support. This helps move items like this up the backlog. You may also consider reaching out to your Adobe CSM as they can help drive these requests further.
 
@blender,
Thank you for your feedback. We try hard to keep communication open on these tickets. Sometimes the enhancement requests are not updated for some time due to many others being addressed. We will continue to strive to do better and support this community.

**Comment by blender** [comment]
I think that the same amount of time and characters that you have typed in this post is about what it take to add binary project support.

Towards the bottom: https://github.com/Carthage/Carthage/blob/master/Documentation/Artifacts.md

**Comment by constanceyang** [comment]
Just wonder when carthage will support?

**Comment by damien-nd** [comment]
+1 @blender ;)
So not in first half of 2018 means that it is expected in more than 6 months?
And the same for bitcode? You do it for Watch but not for basic, extension or TV one?
@hunterpeterson It doesn't look like more than an hour of work but we will never have it?

**Comment by walsht** [comment]
+1

**Comment by samscam** [comment]
This actually almost works in a hacky way - if you add the repo into your cartfile like so:

`github "Adobe-Marketing-Cloud/mobile-services" "v4.15.0-iOS"`

... noting that you need to give the full tag as carthage interprets anything with a `-something` suffix as being pre-release...

Carthage will clone the repo into `Carthage/Checkouts/mobile-services`

You can then link your app to the `ADBMobile.h` and `ADBMobileLibrary.a` from deep in `Carthage/Checkouts/mobile-services/sdks/iOS/AdobeMobileLibrary/`

It's not pretty but it does work. You also don't get half the benefits of Carthage in being able to check for outdatedness or semantic versioning etc -- but at least you can manage the dependency from your Cartfile.

Proper support for Carthage would be both easily done and much appreciated.

**Comment by t-unit** [comment]
+1

**Comment by punty** [comment]
+1

**Comment by Harout360** [comment]
+1

**Comment by praschetan** [comment]
We have no current plans to support Carthage. We may with our new SDKs (found here - https://github.com/Adobe-Marketing-Cloud/acp-sdks/ ), but no firm plans, yet.
