### ISSUE TITLE
Asset Satellite json not found (404)

### ISSUE THREAD

**Issue by stenanderssen** [Adobe-Marketing-Cloud/mobile-services#232]
Hi,

We are currently using the Adobe Mobile Service SDK for iOS (4.13.8) in an iPad app. In our network tracking monitoring tool we found out that some requests to http://assets.adobedtm.com/.../scripts/satellite-...json return with 404. Mostly with the same request url. 
I just wanted to verify if there is something we can do about this problem or wether the problem lies on our side.

Cheers,
Sten

**Comment by sbenedicadb** [comment]
Hey @stenanderssen,

These requests are to Adobe DTM, where your remote settings for In-App Messaging and Points of Interest are hosted.  The remote files are created for you automatically when you use either of those two capabilities.  Since you are getting a 404, I'm guessing you don't use either capability in your app.  The errors themselves are harmless, but if you'd like to stop making the network calls, you can do so by removing the `remotes` object from your `ADBMobileConfig.json` file.  Note that by doing this, you will be disabling remote modification of In-App Messages and Points of Interest for your app.

Hope this helps.

**steve benedick**
*sr mobile software engineer*
[Adobe Marketing Cloud](http://www.adobe.com/solutions/digital-marketing.html)

**Comment by stenanderssen** [comment]
Hi @sbenedicadb,

Tank you for your quick response and detailed answer. No we understand whats happening and will take necessary actions to resolve this problem. 

Cheers,
Sten
