### ISSUE TITLE
Why can't I call `[ADBMobile overrideConfigPath:filePath];` outside of `didFinishLaunchingWithOptions`

### ISSUE THREAD

**Issue by robotsquidward** [Adobe-Marketing-Cloud/mobile-services#240]
Because of the limitations of our app architecture, we would like to have more fine grained control over when SDK methods (including lifecycle metrics calls) are called in the application.

Why does `overrideConfigPath` need to be called inside of `didFinishLaunchingWithOptions`?  I'm curious as to the technical reason, not the logical reason that it is the starting point of the app.

**Comment by sbenedicadb** [comment]
Hey @robotsquidward,

We are using a C constructor attribute in the v4 iOS SDK to automatically start lifecycle when your app loads (providing you have any calls to the SDK in your app).  This code is executed at the end of `didFinishLaunchingWithOptions` or during your first interaction with the SDK, whichever comes first.  Because the SDK only allows configuration to be loaded once per run, the message to `overrideConfigPath` must be sent as your first usage of the SDK.

**steve benedick**
*sr mobile software engineer*
[Adobe Marketing Cloud](http://www.adobe.com/solutions/digital-marketing.html)
