### ISSUE TITLE
Enabling Video Heartbeat

### ISSUE THREAD

**Issue by brennan** [Adobe-Marketing-Cloud/mobile-services#244]
I'm in the process of enabling Video Heartbeat for testing purposes. Your documentation indicates that enabling Visitor ID service is one prerequisite to using Video Heartbeat. I notice in my Mobile Services dashboard that to enable Visitor ID service for Android, I must "log in with an Adobe ID". My Adobe ID is not recognized by the Mobile Services dashboard. 

Your [documentation here](https://marketing.adobe.com/resources/help/en_US/mobile/android/requirements.html) suggests that I can connect my Adobe ID with my organization in order to log into Mobile Services with an Adobe ID - but the page is missing. Also, the main Marketing Cloud [login link here](https://login.marketing.adobe.com/content/mac/default/tools/accountslinking.html?promoid=VTC5K7T1&amp;mv=other) is dead - this is the link on the [Adobe Marketing Cloud homepage here](http://www.adobe.com/marketing-cloud.html).

Do you have more information on how I can enable the Visitor ID service and link an Adobe ID to an organization Marketing Cloud account? Thanks!

**Comment by shalehaha** [comment]
@brennan,

I can access the login page https://login.marketing.adobe.com/, can you try again or try it on another device?

**Comment by brennan** [comment]
@shalehaha Unfortunately, I get the same error even after restarting my machine and clearing my browser cookies. 

Do you also have more information on linking an Adobe ID to a mobile services dashboard? Thanks!

**Comment by ahmyr** [comment]
@shalehaha, marketing.adobe.com is the link for the Marketing Cloud, so that should work. Are you getting a page not found error or something? Works fine for me as well.

For linking an Adobe ID, you'll first need to have the Marketing Cloud admin for your company or organization provision your Adobe ID with access for Adobe Analytics. Once this is done, you can go to mobilemarketing.adobe.com and login with your Adobe ID. 

If this has already been done, and it still doesn't work, trying logging in with your Adobe ID at marketing.adobe.com. Then, switch to Analytics (click the square of nine dots in the upper-right and then choose Analytics from the dropdown that appears). If your Analytics account and Adobe ID account are not already linked, it should give you a dialog for linking your accounts. You can put your Analytics company, username, and password in the dialog there to link them. Once they are linked successfully, then you can go back to mobilemarketing.adobe.com and login with your Adobe ID.

**Comment by brennan** [comment]
Thanks @ahmyr - I'm able to get to the Adobe Marketing Cloud page [here](https://www.dropbox.com/s/sj08ye2wdjvjuue/Screenshot%202017-11-29%2008.40.50.png?dl=0), but once I click "Sign In", I get [this error](https://www.dropbox.com/s/vxmjkwyk3uhsfln/Screenshot%202017-11-29%2008.41.47.png?dl=0). My Adobe ID has already been provisioned access to Adobe Analytics because I'm able to log in to the Analytics dashboard with my personal Adobe ID, but I'm still unable to access Mobile Services with this ID. I confirmed the association was successful via email with your support team on Nov. 8.

**Comment by brennan** [comment]
@ahmyr @shalehaha Is one of you able to join a call to troubleshoot this issue? Unfortunately because I can't even access Adobe Marketing Cloud with my Adobe ID, I can't follow the steps outlined above. Thanks!

**Comment by hunterpeterson** [comment]
@brennan,
In order to get more detailed information and reproduce the issue internally, please reach out to [client care](http://helpx.adobe.com/marketing-cloud/contact-support.html).

**Comment by brennan** [comment]
Hey @hunterpeterson - I've reached out to client care three times since Monday, with no reply so far, as well as on Twitter. Here's a [gif of what I'm seeing](https://gyazo.com/137e3079c75c2d84385b92efd22fff69) - it's unlikely a 500 error is specific to my machine. My Adobe ID is tools+adobe@segment.com. cc @shalehaha @ahmyr Thanks!

**Comment by hunterpeterson** [comment]
@brennan,
I have reached out to Client Care asking them to contact you. We will get this fixed.

**Comment by hunterpeterson** [comment]
@brennan,
Looks like your ticket ended up in a different queue than Client Care. Looks like there is some movement now. Have you received any communication at this point?

**Comment by brennan** [comment]
Yes, @hunterpeterson - thanks for checking in. Someone reached out to me about an hour ago.

**Comment by ahmyr** [comment]
@brennan, please let us know if they aren't able to resolve it quickly and I'll work with them.
