### ISSUE TITLE
Android Binaries on jcenter don't match the ones in the release section

### ISSUE THREAD

**Issue by pbreault** [Adobe-Marketing-Cloud/mobile-services#252]
The binaries for version `4.14.0-Android` on [jcenter](http://jcenter.bintray.com/com/adobe/mobile/adobeMobileLibrary/) are different than the ones in the [release page](https://github.com/Adobe-Marketing-Cloud/mobile-services/releases/tag/v4.14.0-Android).

jcenter’s shasum: `d2a90fc1b1dd852d74950c0ea120e0fa57934d14`
github’s shasum: `7dfcca53c1c01512c9a8d6953a5193c2a7a6e777`

We would expect both to be identical.

**Comment by shalehaha** [comment]
@pbreault,
The binary on jcenter and the one in the release page are built from different processes, so the shasum values are not identical. 

Is there any concern about this or does it bring any problem to your project? Thanks.


**Jiabin Geng**
* mobile software engineer*
[Adobe Marketing Cloud](http://www.adobe.com/solutions/digital-marketing.html)

**Comment by subhowmi** [comment]
@pbreault ,
Like @shalehaha  mentioned above, the bintray upload is done using a different build process that needs to build the artifacts again, which causes the jar headers to be different due to the timestamps of the compiled binary. The artifacts on Github and JCenter are functionally the same. We have raised an issue internally to address this concern and will be tweaking the process for future releases to make sure that this difference is eliminated. 

Hope this helps with your concerns. Let us know if you have any other questions.

Thanks,

**Sudeep Bhowmick**
*mobile software engineer*
[Adobe Marketing Cloud](http://www.adobe.com/solutions/digital-marketing.html)

**Comment by pbreault** [comment]
Thank you for the clarification. This was more of a general concern when trying to find out which version should be used between the one on github, on jcenter or on maven central. This is not a blocker in any way.
