### ISSUE TITLE
Unity SDK is horribly out of date

### ISSUE THREAD

**Issue by sam-eller** [Adobe-Marketing-Cloud/mobile-services#313]
Last update was from October 2016. The version of the Adobe Analytics SDK for Unity doesn't work on iOS 11+ according to your own documentation. 4.13.1 is the Unity plugin version, and 4.13.8 or later is needed according to your own site's documentation.
Can we please get an update to this SDK soon?

**Comment by steve-ddigital** [comment]
I downloaded and installed the Unity package, and then dropped in the latest releases of the iOS and Android libraries.  Comparing the iOS header files, there have been very few changes, mostly additional functions, so that shouldn't be an issue.  It appears to work (as far as I can tell), but perhaps I'll try the web API as well.

@imironchuk mentioned in the [new repo](https://github.com/Adobe-Marketing-Cloud/acp-sdks/issues/130) that Unity is still supported, despite the evidence to the contrary.

**Comment by ahmyr** [comment]
We are taking a look and will report back.

**Comment by PravinPK** [comment]
@sam-eller like @steve-ddigital mentioned dropping the latest version of iOS and Android binary files (.a and .jar) will work. All 4.x versions are guaranteed to be backwards compatible. There is nothing compiled in the unity package distribution itself (besides the `.a` and `.jar` files), so if you need access to one of the newer apis, you can write a quick method to wrap it and go from there. 

You can find the latest binaries here : https://github.com/Adobe-Marketing-Cloud/mobile-services/tree/master/sdks

**Comment by Coeur** [comment]
> you can write a quick method to wrap it

You mean that Adobe will quickly fix it? ;)

**Comment by sbenedicadb** [comment]
Hey all,

The Unity package was updated recently: https://github.com/Adobe-Marketing-Cloud/mobile-services/releases/tag/v4.18.8-Unity

Closing this issue.
