### ISSUE TITLE
Crashes reported is extremely high

### ISSUE THREAD

**Issue by kerrmarin** [Adobe-Marketing-Cloud/mobile-services#69]
Hi there,

I have an app that uses Omniture's iOS SDK to report analytics. The number of crashes reported in the dashboard is extremely high. I know for a fact that the app does **not** crash that often (reports are crash rate of  ~50% of sessions).

I've been unable to find a definition of "crash" for Adobe and the current metrics are useless. Is this something that can be fixed?

**Comment by hunterpeterson** [comment]
Hey kerrmarin,
Thank you for contacting us about the issue. A "crash" in the Adobe SDK is any time the application does not close gracefully. Would you mind opening an issue with [client care](http://helpx.adobe.com/marketing-cloud/contact-support.html) so that we can get more information from you?

**Hunter Peterson**
*Sr. Mobile Engineer*
[Adobe Marketing Cloud](http://www.adobe.com/solutions/digital-marketing.html)

**Comment by kerrmarin** [comment]
Hey Hunter,

Can you define "close gracefully"? Is that the only time the SDK will send a crash or are there any other times? e.g. background processes, etc?

I tried to find a link to contact someone through client care but it seems impossible so I gave up on that.

Thanks

**Comment by hunterpeterson** [comment]
Hey Kerrmarin,
Sorry for the delay. "Close gracefully" meaning it went through apple/googles normal application lifecycle for the close. Also yes, as you said, another situation that could cause this is calling track calls without using trackActionFromBackground when tracking something within a background process on iOS. 

**Hunter Peterson**
*Sr. Mobile Engineer*
[Adobe Marketing Cloud](http://www.adobe.com/solutions/digital-marketing.html)

**Comment by sam899** [comment]
Hi @kerrmarin 

Did you manage to find a solution for this? I'm seeing extremely high traffic for Crash & Lifecycle events using v4.5.5 of the SDK.

**Comment by kerrmarin** [comment]
hi @sam899. The conclusion I got to is that I think the way Adobe report crashes is wrong. Anything that isn't a "graceful close" is reported as a crash. Here's a list of things that can cause an app to close "ungracefully":

- The app was upgraded.
- The app called exit or abort.
- The app crashed.
- A user swiped up to force-exit the application.
- The device restarted (which includes an OS upgrade).
- The app ran out of memory (an OOM) in the background or the foreground.

Only 2, of these are actually crashes I'm interested in though. Solution is to use a different provider for analytics, or at a minimum a different provider for an accurate representation of crashes.

Cheers

**Comment by sbenedicadb** [comment]
Hey @sam899, @kerrmarin,

A "graceful close" is meant to represent any scenario where the user entered the background before the app was closed (whether by the user or by the OS).  Currently, the predominant cause of a "false positive" crash being reported is due to backgrounded activity not being handled properly by the SDK.  We are working on a fix that prevent those false positives from happening. 

From the testing we have done, the following scenarios alone will **not** cause a crash to be reported:

- An app upgrade
- A manual close by the user from the Multitasking view
- A device restart

@kerrmarin - If you are seeing any of these three scenarios cause a false crash, could you please contact [Client Care](http://helpx.adobe.com/marketing-cloud/contact-support.html) and open a ticket with reproducible steps? We are always trying to improve and would love to fix any of these issues you may be seeing.

Most of the time if the app runs out of memory while in the background, it has already been affected by the background issue mentioned earlier, so it will be reported falsely as a crash.

We will report the rest of the items as crashes (including OOM in foreground, if it results in an exception).  

Hope this helps.

**steve benedick**
*sr mobile software engineer*
[Adobe Marketing Cloud](http://www.adobe.com/solutions/digital-marketing.html)

**Comment by sam899** [comment]
Thanks @sbenedicadb 

Is it possible to disable this crash analytics reporting at all? We dont use these anyway as we use Crashlytics for reporting crashing.

**Comment by cosminstirbu** [comment]
Hi,

I'm also interested in disabling this metric.
Is there any way we can do this?

Thank you,
Cosmin

**Comment by sbenedicadb** [comment]
Hey @cosminstirbu (and @sam899),

Crash reporting is part of lifecycle we collect automatically in the iOS SDK.  You can't disable the collection of it.  

If you want to prevent the mapping of the variable that generates the crash report, you might be able to do that.  I'd recommend contacting your Analytics account manager to see if they can help you with that.

Hope this helps.

**steve benedick**
*sr mobile software engineer*
[Adobe Experience Cloud](http://www.adobe.com/experience-cloud.html)

**Comment by thornbrook** [comment]
Hi @cosminstirbu / @sam899

Did either of you end up resolving this issue for yourselves?

This is an exact replica of a situation we are facing - where crashes are heavily inflated and then inflating Visit counts, negatively skewing Conversion Rate, etc.

**Comment by cosminstirbu** [comment]
For now we simply ignore it - and I'm not sure we do anything special to ignore it, as I am on the development side, and I'm not too familiar with configuring the "backend / mappings" in Adobe.
