### ISSUE TITLE
iOS call to class method `trackingIdentifier` returns nil

### ISSUE THREAD

**Issue by nsnutella** [Adobe-Marketing-Cloud/mobile-services#93]
Hi,

We're iOS developers to the Net-A-Porter group.

We're having a problem related with the call to `trackingIdentifier` on `ADBMobile` class. The call to this method is returning `nil`. That was not happening on version 4.0.2, so you have changed something that we miss.
The call to this method is done on the `application:didFinishLaunchingWithOptions:

In the 4.3 version you add a note that says `This method can cause a blocking network call and should not be used from a UI thread.`
We need to change this, but why is this relevant? Why this call returns `nil` and not a valid `NSString*`?

Really appreciate your help on this.
Many Thanks

**Comment by shalehaha** [comment]
@nsnutella ,

From version 4.3.0 we introduced the support for Adobe Marketing Cloud ID, so if you app is Marketing Cloud enabled and you didn't setup a grace period for it, then SDK will return nil for trackingIdentifier call on a new installed app. 
Because trackingIdentifier is a sync call running on a background queue, so it could potentially take a long time, and if you put it on a UI thread then it would block the UI operation.
Thanks,
-Jiabin
